# Generated by Django 3.0.5 on 2020-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('term', models.PositiveIntegerField()),
                ('summary', models.FloatField()),
                ('percent', models.PositiveIntegerField()),
                ('profit', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('open_state', models.BooleanField()),
            ],
        ),
    ]
