# Generated by Django 3.0.5 on 2020-04-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esInvestApp', '0002_deal_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='owner',
        ),
    ]
