# Generated by Django 3.0.5 on 2020-04-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esInvestApp', '0005_auto_20200411_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='owner',
        ),
    ]
