# Generated by Django 3.0.5 on 2020-04-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esInvestApp', '0007_deal_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='open_state',
        ),
    ]
