# Generated by Django 3.0.5 on 2020-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esInvestApp', '0008_remove_deal_open_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
