# Generated by Django 3.0.5 on 2020-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esInvestApp', '0009_deal_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='invest_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
